---
- name: Download glassfish
  get_url:
    url: "{{ glassfish_mirror }}/{{ glassfish_redis_filename }}"
    dest: "{{ glassfish_download_dir }}/{{ glassfish_redis_filename }}"
    mode: "0644"
    timeout: 1000
- name: create Glassfish installation directory
  become: yes
  file:
    state: directory
    owner: root
    group: root
    mode: "0755"
    dest: "{{ glassfish_install_dir }}"
- name: install Glassfish
  become: yes
  unarchive:
    src: "{{ glassfish_download_dir }}/{{ glassfish_redis_filename }}"
    dest: "{{ glassfish_install_dir }}"
    copy: false
    owner: root
    group: root
    mode: "0755"
- name: Add asadmin to {{ glassfish_user }} bashrc
  lineinfile: dest=/home/{{ glassfish_user }}/.bashrc 
       line='export PATH={{ glassfish_install_dir}}/{{ glassfish_product }}/bin:$PATH' 
       insertafter='EOF' 
       state=present
- name: Copy password file to tmp
  become: yes
  template:
    src: password.j2 
    dest: "{{ glassfish_download_dir }}/password.txt"
    owner: root
    group: root
    mode: "0755"
- name: Change admin password
  command: >
   {{ glassfish_install_dir}}/{{ glassfish_product }}/bin/asadmin 
   --user admin 
   --passwordfile {{ glassfish_download_dir }}/password.txt 
   change-admin-password 
   --domain_name domain1
- name: put default admin password in file.
  lineinfile: dest={{ glassfish_download_dir}}/password.txt
    regexp='AS_ADMIN_PASSWORD='
    line='AS_ADMIN_PASSWORD=admin'
    state=present    
- name: Start/stop domain1 introducing security password.
  shell: "{{ glassfish_install_dir}}/{{ glassfish_product }}/bin/asadmin start-domain && {{ glassfish_install_dir}}/{{ glassfish_product }}/bin/asadmin --passwordfile /tmp/password.txt --host localhost --port 4848 enable-secure-admin && {{ glassfish_install_dir}}/{{ glassfish_product }}/bin/asadmin stop-domain"
 
- include: connectorJ.yml
- name: Removing password file
  file: path="{{ glassfish_download_dir}}/password.txt"
    state=absent
- name: Removing Glassfish/Payara file
  file: path="{{ glassfish_download_dir }}/{{ glassfish_redis_filename }}"
   state=absent
- name: Fixing ownership for domain1 directory
  become: yes
  file:
    state: directory
    owner: "{{ glassfish_user }}"
    recurse: yes
    mode: "0755"
    dest: "{{ glassfish_install_dir}}/{{ glassfish_product }}/glassfish/domains/domain1"
- name: "copy init script"
  become: yes
  action: template src=etc/init.d/glassfish dest=/etc/init.d/glassfish owner=root group=root mode=0754
- name: Starting Glassfish/Payara with domain1
  become: yes
  shell: "/etc/init.d/glassfish start"
